/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AAdditionAddition extends PAddition
{
    private PAddition _addition_;
    private TPlus _plus_;
    private PMultiplication _multiplication_;

    public AAdditionAddition()
    {
    }

    public AAdditionAddition(
        PAddition _addition_,
        TPlus _plus_,
        PMultiplication _multiplication_)
    {
        setAddition(_addition_);

        setPlus(_plus_);

        setMultiplication(_multiplication_);

    }
    public Object clone()
    {
        return new AAdditionAddition(
            (PAddition) cloneNode(_addition_),
            (TPlus) cloneNode(_plus_),
            (PMultiplication) cloneNode(_multiplication_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAdditionAddition(this);
    }

    public PAddition getAddition()
    {
        return _addition_;
    }

    public void setAddition(PAddition node)
    {
        if(_addition_ != null)
        {
            _addition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _addition_ = node;
    }

    public TPlus getPlus()
    {
        return _plus_;
    }

    public void setPlus(TPlus node)
    {
        if(_plus_ != null)
        {
            _plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _plus_ = node;
    }

    public PMultiplication getMultiplication()
    {
        return _multiplication_;
    }

    public void setMultiplication(PMultiplication node)
    {
        if(_multiplication_ != null)
        {
            _multiplication_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _multiplication_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_addition_)
            + toString(_plus_)
            + toString(_multiplication_);
    }

    void removeChild(Node child)
    {
        if(_addition_ == child)
        {
            _addition_ = null;
            return;
        }

        if(_plus_ == child)
        {
            _plus_ = null;
            return;
        }

        if(_multiplication_ == child)
        {
            _multiplication_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_addition_ == oldChild)
        {
            setAddition((PAddition) newChild);
            return;
        }

        if(_plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(_multiplication_ == oldChild)
        {
            setMultiplication((PMultiplication) newChild);
            return;
        }

    }
}
