/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AAndComparisons extends PComparisons
{
    private PComparisons _c1_;
    private PComparisons _c2_;

    public AAndComparisons()
    {
    }

    public AAndComparisons(
        PComparisons _c1_,
        PComparisons _c2_)
    {
        setC1(_c1_);

        setC2(_c2_);

    }
    public Object clone()
    {
        return new AAndComparisons(
            (PComparisons) cloneNode(_c1_),
            (PComparisons) cloneNode(_c2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndComparisons(this);
    }

    public PComparisons getC1()
    {
        return _c1_;
    }

    public void setC1(PComparisons node)
    {
        if(_c1_ != null)
        {
            _c1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _c1_ = node;
    }

    public PComparisons getC2()
    {
        return _c2_;
    }

    public void setC2(PComparisons node)
    {
        if(_c2_ != null)
        {
            _c2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _c2_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_c1_)
            + toString(_c2_);
    }

    void removeChild(Node child)
    {
        if(_c1_ == child)
        {
            _c1_ = null;
            return;
        }

        if(_c2_ == child)
        {
            _c2_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_c1_ == oldChild)
        {
            setC1((PComparisons) newChild);
            return;
        }

        if(_c2_ == oldChild)
        {
            setC2((PComparisons) newChild);
            return;
        }

    }
}
