/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AAndComparisonAnd extends PComparisonAnd
{
    private PComparisonAnd _comparisonAnd_;
    private TAnd _and_;
    private PComparisonNot _comparisonNot_;

    public AAndComparisonAnd()
    {
    }

    public AAndComparisonAnd(
        PComparisonAnd _comparisonAnd_,
        TAnd _and_,
        PComparisonNot _comparisonNot_)
    {
        setComparisonAnd(_comparisonAnd_);

        setAnd(_and_);

        setComparisonNot(_comparisonNot_);

    }
    public Object clone()
    {
        return new AAndComparisonAnd(
            (PComparisonAnd) cloneNode(_comparisonAnd_),
            (TAnd) cloneNode(_and_),
            (PComparisonNot) cloneNode(_comparisonNot_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndComparisonAnd(this);
    }

    public PComparisonAnd getComparisonAnd()
    {
        return _comparisonAnd_;
    }

    public void setComparisonAnd(PComparisonAnd node)
    {
        if(_comparisonAnd_ != null)
        {
            _comparisonAnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comparisonAnd_ = node;
    }

    public TAnd getAnd()
    {
        return _and_;
    }

    public void setAnd(TAnd node)
    {
        if(_and_ != null)
        {
            _and_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _and_ = node;
    }

    public PComparisonNot getComparisonNot()
    {
        return _comparisonNot_;
    }

    public void setComparisonNot(PComparisonNot node)
    {
        if(_comparisonNot_ != null)
        {
            _comparisonNot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comparisonNot_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_comparisonAnd_)
            + toString(_and_)
            + toString(_comparisonNot_);
    }

    void removeChild(Node child)
    {
        if(_comparisonAnd_ == child)
        {
            _comparisonAnd_ = null;
            return;
        }

        if(_and_ == child)
        {
            _and_ = null;
            return;
        }

        if(_comparisonNot_ == child)
        {
            _comparisonNot_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_comparisonAnd_ == oldChild)
        {
            setComparisonAnd((PComparisonAnd) newChild);
            return;
        }

        if(_and_ == oldChild)
        {
            setAnd((TAnd) newChild);
            return;
        }

        if(_comparisonNot_ == oldChild)
        {
            setComparisonNot((PComparisonNot) newChild);
            return;
        }

    }
}
