/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AArguements extends PArguements
{
    private TId _id_;
    private final LinkedList _value_ = new TypedLinkedList(new Value_Cast());
    private final LinkedList _multipleargs_ = new TypedLinkedList(new Multipleargs_Cast());

    public AArguements()
    {
    }

    public AArguements(
        TId _id_,
        List _value_,
        List _multipleargs_)
    {
        setId(_id_);

        {
            this._value_.clear();
            this._value_.addAll(_value_);
        }

        {
            this._multipleargs_.clear();
            this._multipleargs_.addAll(_multipleargs_);
        }

    }
    public Object clone()
    {
        return new AArguements(
            (TId) cloneNode(_id_),
            cloneList(_value_),
            cloneList(_multipleargs_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArguements(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public LinkedList getValue()
    {
        return _value_;
    }

    public void setValue(List list)
    {
        _value_.clear();
        _value_.addAll(list);
    }

    public LinkedList getMultipleargs()
    {
        return _multipleargs_;
    }

    public void setMultipleargs(List list)
    {
        _multipleargs_.clear();
        _multipleargs_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_value_)
            + toString(_multipleargs_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_value_.remove(child))
        {
            return;
        }

        if(_multipleargs_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator i = _value_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator i = _multipleargs_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Value_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PValue node = (PValue) o;

            if((node.parent() != null) &&
                (node.parent() != AArguements.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AArguements.this))
            {
                node.parent(AArguements.this);
            }

            return node;
        }
    }

    private class Multipleargs_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PMultipleargs node = (PMultipleargs) o;

            if((node.parent() != null) &&
                (node.parent() != AArguements.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AArguements.this))
            {
                node.parent(AArguements.this);
            }

            return node;
        }
    }
}
