/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AAssertStatement extends PStatement
{
    private PExpression _l_;
    private final LinkedList _commaExp_ = new TypedLinkedList(new CommaExp_Cast());

    public AAssertStatement()
    {
    }

    public AAssertStatement(
        PExpression _l_,
        List _commaExp_)
    {
        setL(_l_);

        {
            this._commaExp_.clear();
            this._commaExp_.addAll(_commaExp_);
        }

    }
    public Object clone()
    {
        return new AAssertStatement(
            (PExpression) cloneNode(_l_),
            cloneList(_commaExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssertStatement(this);
    }

    public PExpression getL()
    {
        return _l_;
    }

    public void setL(PExpression node)
    {
        if(_l_ != null)
        {
            _l_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _l_ = node;
    }

    public LinkedList getCommaExp()
    {
        return _commaExp_;
    }

    public void setCommaExp(List list)
    {
        _commaExp_.clear();
        _commaExp_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_l_)
            + toString(_commaExp_);
    }

    void removeChild(Node child)
    {
        if(_l_ == child)
        {
            _l_ = null;
            return;
        }

        if(_commaExp_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_l_ == oldChild)
        {
            setL((PExpression) newChild);
            return;
        }

        for(ListIterator i = _commaExp_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class CommaExp_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PExpression node = (PExpression) o;

            if((node.parent() != null) &&
                (node.parent() != AAssertStatement.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AAssertStatement.this))
            {
                node.parent(AAssertStatement.this);
            }

            return node;
        }
    }
}
