/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ACidentAsIdent extends PCidentAsIdent
{
    private TId _id_;
    private final LinkedList _asIdent_ = new TypedLinkedList(new AsIdent_Cast());

    public ACidentAsIdent()
    {
    }

    public ACidentAsIdent(
        TId _id_,
        List _asIdent_)
    {
        setId(_id_);

        {
            this._asIdent_.clear();
            this._asIdent_.addAll(_asIdent_);
        }

    }
    public Object clone()
    {
        return new ACidentAsIdent(
            (TId) cloneNode(_id_),
            cloneList(_asIdent_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACidentAsIdent(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public LinkedList getAsIdent()
    {
        return _asIdent_;
    }

    public void setAsIdent(List list)
    {
        _asIdent_.clear();
        _asIdent_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_asIdent_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_asIdent_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator i = _asIdent_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class AsIdent_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PAsIdent node = (PAsIdent) o;

            if((node.parent() != null) &&
                (node.parent() != ACidentAsIdent.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ACidentAsIdent.this))
            {
                node.parent(ACidentAsIdent.this);
            }

            return node;
        }
    }
}
