/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ADoubleQuoteStringValue extends PValue
{
    private TStringDoubleQuote _stringDoubleQuote_;

    public ADoubleQuoteStringValue()
    {
    }

    public ADoubleQuoteStringValue(
        TStringDoubleQuote _stringDoubleQuote_)
    {
        setStringDoubleQuote(_stringDoubleQuote_);

    }
    public Object clone()
    {
        return new ADoubleQuoteStringValue(
            (TStringDoubleQuote) cloneNode(_stringDoubleQuote_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADoubleQuoteStringValue(this);
    }

    public TStringDoubleQuote getStringDoubleQuote()
    {
        return _stringDoubleQuote_;
    }

    public void setStringDoubleQuote(TStringDoubleQuote node)
    {
        if(_stringDoubleQuote_ != null)
        {
            _stringDoubleQuote_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _stringDoubleQuote_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_stringDoubleQuote_);
    }

    void removeChild(Node child)
    {
        if(_stringDoubleQuote_ == child)
        {
            _stringDoubleQuote_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_stringDoubleQuote_ == oldChild)
        {
            setStringDoubleQuote((TStringDoubleQuote) newChild);
            return;
        }

    }
}
