/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AForStatement extends PStatement
{
    private TId _element_;
    private TId _collection_;
    private PStatement _statement_;

    public AForStatement()
    {
    }

    public AForStatement(
        TId _element_,
        TId _collection_,
        PStatement _statement_)
    {
        setElement(_element_);

        setCollection(_collection_);

        setStatement(_statement_);

    }
    public Object clone()
    {
        return new AForStatement(
            (TId) cloneNode(_element_),
            (TId) cloneNode(_collection_),
            (PStatement) cloneNode(_statement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForStatement(this);
    }

    public TId getElement()
    {
        return _element_;
    }

    public void setElement(TId node)
    {
        if(_element_ != null)
        {
            _element_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _element_ = node;
    }

    public TId getCollection()
    {
        return _collection_;
    }

    public void setCollection(TId node)
    {
        if(_collection_ != null)
        {
            _collection_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _collection_ = node;
    }

    public PStatement getStatement()
    {
        return _statement_;
    }

    public void setStatement(PStatement node)
    {
        if(_statement_ != null)
        {
            _statement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _statement_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_element_)
            + toString(_collection_)
            + toString(_statement_);
    }

    void removeChild(Node child)
    {
        if(_element_ == child)
        {
            _element_ = null;
            return;
        }

        if(_collection_ == child)
        {
            _collection_ = null;
            return;
        }

        if(_statement_ == child)
        {
            _statement_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_element_ == oldChild)
        {
            setElement((TId) newChild);
            return;
        }

        if(_collection_ == oldChild)
        {
            setCollection((TId) newChild);
            return;
        }

        if(_statement_ == oldChild)
        {
            setStatement((PStatement) newChild);
            return;
        }

    }
}
