/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AFromImportImportCall extends PImportCall
{
    private TFrom _from_;
    private PModule _module_;
    private TImport _import_;
    private TId _id_;
    private PAsIdent _asIdent_;
    private final LinkedList _cidentAsIdent_ = new TypedLinkedList(new CidentAsIdent_Cast());

    public AFromImportImportCall()
    {
    }

    public AFromImportImportCall(
        TFrom _from_,
        PModule _module_,
        TImport _import_,
        TId _id_,
        PAsIdent _asIdent_,
        List _cidentAsIdent_)
    {
        setFrom(_from_);

        setModule(_module_);

        setImport(_import_);

        setId(_id_);

        setAsIdent(_asIdent_);

        {
            this._cidentAsIdent_.clear();
            this._cidentAsIdent_.addAll(_cidentAsIdent_);
        }

    }
    public Object clone()
    {
        return new AFromImportImportCall(
            (TFrom) cloneNode(_from_),
            (PModule) cloneNode(_module_),
            (TImport) cloneNode(_import_),
            (TId) cloneNode(_id_),
            (PAsIdent) cloneNode(_asIdent_),
            cloneList(_cidentAsIdent_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFromImportImportCall(this);
    }

    public TFrom getFrom()
    {
        return _from_;
    }

    public void setFrom(TFrom node)
    {
        if(_from_ != null)
        {
            _from_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _from_ = node;
    }

    public PModule getModule()
    {
        return _module_;
    }

    public void setModule(PModule node)
    {
        if(_module_ != null)
        {
            _module_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _module_ = node;
    }

    public TImport getImport()
    {
        return _import_;
    }

    public void setImport(TImport node)
    {
        if(_import_ != null)
        {
            _import_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _import_ = node;
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public PAsIdent getAsIdent()
    {
        return _asIdent_;
    }

    public void setAsIdent(PAsIdent node)
    {
        if(_asIdent_ != null)
        {
            _asIdent_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _asIdent_ = node;
    }

    public LinkedList getCidentAsIdent()
    {
        return _cidentAsIdent_;
    }

    public void setCidentAsIdent(List list)
    {
        _cidentAsIdent_.clear();
        _cidentAsIdent_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_from_)
            + toString(_module_)
            + toString(_import_)
            + toString(_id_)
            + toString(_asIdent_)
            + toString(_cidentAsIdent_);
    }

    void removeChild(Node child)
    {
        if(_from_ == child)
        {
            _from_ = null;
            return;
        }

        if(_module_ == child)
        {
            _module_ = null;
            return;
        }

        if(_import_ == child)
        {
            _import_ = null;
            return;
        }

        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_asIdent_ == child)
        {
            _asIdent_ = null;
            return;
        }

        if(_cidentAsIdent_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_from_ == oldChild)
        {
            setFrom((TFrom) newChild);
            return;
        }

        if(_module_ == oldChild)
        {
            setModule((PModule) newChild);
            return;
        }

        if(_import_ == oldChild)
        {
            setImport((TImport) newChild);
            return;
        }

        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(_asIdent_ == oldChild)
        {
            setAsIdent((PAsIdent) newChild);
            return;
        }

        for(ListIterator i = _cidentAsIdent_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class CidentAsIdent_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PCidentAsIdent node = (PCidentAsIdent) o;

            if((node.parent() != null) &&
                (node.parent() != AFromImportImportCall.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AFromImportImportCall.this))
            {
                node.parent(AFromImportImportCall.this);
            }

            return node;
        }
    }
}
