/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AFunction extends PFunction
{
    private TId _id_;
    private final LinkedList _arguements_ = new TypedLinkedList(new Arguements_Cast());
    private PStatement _statement_;

    public AFunction()
    {
    }

    public AFunction(
        TId _id_,
        List _arguements_,
        PStatement _statement_)
    {
        setId(_id_);

        {
            this._arguements_.clear();
            this._arguements_.addAll(_arguements_);
        }

        setStatement(_statement_);

    }
    public Object clone()
    {
        return new AFunction(
            (TId) cloneNode(_id_),
            cloneList(_arguements_),
            (PStatement) cloneNode(_statement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunction(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public LinkedList getArguements()
    {
        return _arguements_;
    }

    public void setArguements(List list)
    {
        _arguements_.clear();
        _arguements_.addAll(list);
    }

    public PStatement getStatement()
    {
        return _statement_;
    }

    public void setStatement(PStatement node)
    {
        if(_statement_ != null)
        {
            _statement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _statement_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_arguements_)
            + toString(_statement_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_arguements_.remove(child))
        {
            return;
        }

        if(_statement_ == child)
        {
            _statement_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator i = _arguements_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_statement_ == oldChild)
        {
            setStatement((PStatement) newChild);
            return;
        }

    }

    private class Arguements_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PArguements node = (PArguements) o;

            if((node.parent() != null) &&
                (node.parent() != AFunction.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AFunction.this))
            {
                node.parent(AFunction.this);
            }

            return node;
        }
    }
}
