/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AIdentDot extends PIdentDot
{
    private TId _id_;
    private TDot _dot_;

    public AIdentDot()
    {
    }

    public AIdentDot(
        TId _id_,
        TDot _dot_)
    {
        setId(_id_);

        setDot(_dot_);

    }
    public Object clone()
    {
        return new AIdentDot(
            (TId) cloneNode(_id_),
            (TDot) cloneNode(_dot_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdentDot(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public TDot getDot()
    {
        return _dot_;
    }

    public void setDot(TDot node)
    {
        if(_dot_ != null)
        {
            _dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dot_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_dot_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_dot_ == child)
        {
            _dot_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(_dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

    }
}
