/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AImportStatement extends PStatement
{
    private PImportCall _importCall_;

    public AImportStatement()
    {
    }

    public AImportStatement(
        PImportCall _importCall_)
    {
        setImportCall(_importCall_);

    }
    public Object clone()
    {
        return new AImportStatement(
            (PImportCall) cloneNode(_importCall_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAImportStatement(this);
    }

    public PImportCall getImportCall()
    {
        return _importCall_;
    }

    public void setImportCall(PImportCall node)
    {
        if(_importCall_ != null)
        {
            _importCall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _importCall_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_importCall_);
    }

    void removeChild(Node child)
    {
        if(_importCall_ == child)
        {
            _importCall_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_importCall_ == oldChild)
        {
            setImportCall((PImportCall) newChild);
            return;
        }

    }
}
