/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AImportImportCall extends PImportCall
{
    private PModule _module_;
    private final LinkedList _asIdent_ = new TypedLinkedList(new AsIdent_Cast());
    private final LinkedList _cmodAsIdent_ = new TypedLinkedList(new CmodAsIdent_Cast());

    public AImportImportCall()
    {
    }

    public AImportImportCall(
        PModule _module_,
        List _asIdent_,
        List _cmodAsIdent_)
    {
        setModule(_module_);

        {
            this._asIdent_.clear();
            this._asIdent_.addAll(_asIdent_);
        }

        {
            this._cmodAsIdent_.clear();
            this._cmodAsIdent_.addAll(_cmodAsIdent_);
        }

    }
    public Object clone()
    {
        return new AImportImportCall(
            (PModule) cloneNode(_module_),
            cloneList(_asIdent_),
            cloneList(_cmodAsIdent_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAImportImportCall(this);
    }

    public PModule getModule()
    {
        return _module_;
    }

    public void setModule(PModule node)
    {
        if(_module_ != null)
        {
            _module_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _module_ = node;
    }

    public LinkedList getAsIdent()
    {
        return _asIdent_;
    }

    public void setAsIdent(List list)
    {
        _asIdent_.clear();
        _asIdent_.addAll(list);
    }

    public LinkedList getCmodAsIdent()
    {
        return _cmodAsIdent_;
    }

    public void setCmodAsIdent(List list)
    {
        _cmodAsIdent_.clear();
        _cmodAsIdent_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_module_)
            + toString(_asIdent_)
            + toString(_cmodAsIdent_);
    }

    void removeChild(Node child)
    {
        if(_module_ == child)
        {
            _module_ = null;
            return;
        }

        if(_asIdent_.remove(child))
        {
            return;
        }

        if(_cmodAsIdent_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_module_ == oldChild)
        {
            setModule((PModule) newChild);
            return;
        }

        for(ListIterator i = _asIdent_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator i = _cmodAsIdent_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class AsIdent_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PAsIdent node = (PAsIdent) o;

            if((node.parent() != null) &&
                (node.parent() != AImportImportCall.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AImportImportCall.this))
            {
                node.parent(AImportImportCall.this);
            }

            return node;
        }
    }

    private class CmodAsIdent_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PCmodAsIdent node = (PCmodAsIdent) o;

            if((node.parent() != null) &&
                (node.parent() != AImportImportCall.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AImportImportCall.this))
            {
                node.parent(AImportImportCall.this);
            }

            return node;
        }
    }
}
