/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AListExpression extends PExpression
{
    private TLBra _lBra_;
    private PValue _value_;
    private final LinkedList _multipleValues_ = new TypedLinkedList(new MultipleValues_Cast());
    private TRBra _rBra_;

    public AListExpression()
    {
    }

    public AListExpression(
        TLBra _lBra_,
        PValue _value_,
        List _multipleValues_,
        TRBra _rBra_)
    {
        setLBra(_lBra_);

        setValue(_value_);

        {
            this._multipleValues_.clear();
            this._multipleValues_.addAll(_multipleValues_);
        }

        setRBra(_rBra_);

    }
    public Object clone()
    {
        return new AListExpression(
            (TLBra) cloneNode(_lBra_),
            (PValue) cloneNode(_value_),
            cloneList(_multipleValues_),
            (TRBra) cloneNode(_rBra_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListExpression(this);
    }

    public TLBra getLBra()
    {
        return _lBra_;
    }

    public void setLBra(TLBra node)
    {
        if(_lBra_ != null)
        {
            _lBra_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lBra_ = node;
    }

    public PValue getValue()
    {
        return _value_;
    }

    public void setValue(PValue node)
    {
        if(_value_ != null)
        {
            _value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _value_ = node;
    }

    public LinkedList getMultipleValues()
    {
        return _multipleValues_;
    }

    public void setMultipleValues(List list)
    {
        _multipleValues_.clear();
        _multipleValues_.addAll(list);
    }

    public TRBra getRBra()
    {
        return _rBra_;
    }

    public void setRBra(TRBra node)
    {
        if(_rBra_ != null)
        {
            _rBra_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rBra_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lBra_)
            + toString(_value_)
            + toString(_multipleValues_)
            + toString(_rBra_);
    }

    void removeChild(Node child)
    {
        if(_lBra_ == child)
        {
            _lBra_ = null;
            return;
        }

        if(_value_ == child)
        {
            _value_ = null;
            return;
        }

        if(_multipleValues_.remove(child))
        {
            return;
        }

        if(_rBra_ == child)
        {
            _rBra_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lBra_ == oldChild)
        {
            setLBra((TLBra) newChild);
            return;
        }

        if(_value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        for(ListIterator i = _multipleValues_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_rBra_ == oldChild)
        {
            setRBra((TRBra) newChild);
            return;
        }

    }

    private class MultipleValues_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PMultipleValues node = (PMultipleValues) o;

            if((node.parent() != null) &&
                (node.parent() != AListExpression.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AListExpression.this))
            {
                node.parent(AListExpression.this);
            }

            return node;
        }
    }
}
