/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AMinMaxExpression extends PExpression
{
    private PMinMax _minMax_;
    private TLPar _lPar_;
    private PValue _value_;
    private final LinkedList _multipleValues_ = new TypedLinkedList(new MultipleValues_Cast());
    private TRPar _rPar_;

    public AMinMaxExpression()
    {
    }

    public AMinMaxExpression(
        PMinMax _minMax_,
        TLPar _lPar_,
        PValue _value_,
        List _multipleValues_,
        TRPar _rPar_)
    {
        setMinMax(_minMax_);

        setLPar(_lPar_);

        setValue(_value_);

        {
            this._multipleValues_.clear();
            this._multipleValues_.addAll(_multipleValues_);
        }

        setRPar(_rPar_);

    }
    public Object clone()
    {
        return new AMinMaxExpression(
            (PMinMax) cloneNode(_minMax_),
            (TLPar) cloneNode(_lPar_),
            (PValue) cloneNode(_value_),
            cloneList(_multipleValues_),
            (TRPar) cloneNode(_rPar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinMaxExpression(this);
    }

    public PMinMax getMinMax()
    {
        return _minMax_;
    }

    public void setMinMax(PMinMax node)
    {
        if(_minMax_ != null)
        {
            _minMax_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _minMax_ = node;
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PValue getValue()
    {
        return _value_;
    }

    public void setValue(PValue node)
    {
        if(_value_ != null)
        {
            _value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _value_ = node;
    }

    public LinkedList getMultipleValues()
    {
        return _multipleValues_;
    }

    public void setMultipleValues(List list)
    {
        _multipleValues_.clear();
        _multipleValues_.addAll(list);
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_minMax_)
            + toString(_lPar_)
            + toString(_value_)
            + toString(_multipleValues_)
            + toString(_rPar_);
    }

    void removeChild(Node child)
    {
        if(_minMax_ == child)
        {
            _minMax_ = null;
            return;
        }

        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_value_ == child)
        {
            _value_ = null;
            return;
        }

        if(_multipleValues_.remove(child))
        {
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_minMax_ == oldChild)
        {
            setMinMax((PMinMax) newChild);
            return;
        }

        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        for(ListIterator i = _multipleValues_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

    }

    private class MultipleValues_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PMultipleValues node = (PMultipleValues) o;

            if((node.parent() != null) &&
                (node.parent() != AMinMaxExpression.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AMinMaxExpression.this))
            {
                node.parent(AMinMaxExpression.this);
            }

            return node;
        }
    }
}
