/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ASingleQuoteStringValue extends PValue
{
    private TStringSingleQuote _stringSingleQuote_;

    public ASingleQuoteStringValue()
    {
    }

    public ASingleQuoteStringValue(
        TStringSingleQuote _stringSingleQuote_)
    {
        setStringSingleQuote(_stringSingleQuote_);

    }
    public Object clone()
    {
        return new ASingleQuoteStringValue(
            (TStringSingleQuote) cloneNode(_stringSingleQuote_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleQuoteStringValue(this);
    }

    public TStringSingleQuote getStringSingleQuote()
    {
        return _stringSingleQuote_;
    }

    public void setStringSingleQuote(TStringSingleQuote node)
    {
        if(_stringSingleQuote_ != null)
        {
            _stringSingleQuote_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _stringSingleQuote_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_stringSingleQuote_);
    }

    void removeChild(Node child)
    {
        if(_stringSingleQuote_ == child)
        {
            _stringSingleQuote_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_stringSingleQuote_ == oldChild)
        {
            setStringSingleQuote((TStringSingleQuote) newChild);
            return;
        }

    }
}
