/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TLBra extends Token
{
    public TLBra()
    {
        super.setText("[");
    }

    public TLBra(int line, int pos)
    {
        super.setText("[");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLBra(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLBra(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLBra text.");
    }
}
