/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TStringDoubleQuote extends Token
{
    public TStringDoubleQuote()
    {
        super.setText("\"not_eol*\"");
    }

    public TStringDoubleQuote(int line, int pos)
    {
        super.setText("\"not_eol*\"");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TStringDoubleQuote(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStringDoubleQuote(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TStringDoubleQuote text.");
    }
}
