/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TStringSingleQuote extends Token
{
    public TStringSingleQuote(String text)
    {
        setText(text);
    }

    public TStringSingleQuote(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TStringSingleQuote(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStringSingleQuote(this);
    }
}
